// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
)

// NewConfig creates a new instance of Config. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfig(t interface {
	mock.TestingT
	Cleanup(func())
}) *Config {
	mock := &Config{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

type Config_Expecter struct {
	mock *mock.Mock
}

func (_m *Config) EXPECT() *Config_Expecter {
	return &Config_Expecter{mock: &_m.Mock}
}

// DBPath provides a mock function for the type Config
func (_mock *Config) DBPath() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DBPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Config_DBPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DBPath'
type Config_DBPath_Call struct {
	*mock.Call
}

// DBPath is a helper method to define mock.On call
func (_e *Config_Expecter) DBPath() *Config_DBPath_Call {
	return &Config_DBPath_Call{Call: _e.mock.On("DBPath")}
}

func (_c *Config_DBPath_Call) Run(run func()) *Config_DBPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Config_DBPath_Call) Return(s string, err error) *Config_DBPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Config_DBPath_Call) RunAndReturn(run func() (string, error)) *Config_DBPath_Call {
	_c.Call.Return(run)
	return _c
}

// FindProjectRoot provides a mock function for the type Config
func (_mock *Config) FindProjectRoot() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FindProjectRoot")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Config_FindProjectRoot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProjectRoot'
type Config_FindProjectRoot_Call struct {
	*mock.Call
}

// FindProjectRoot is a helper method to define mock.On call
func (_e *Config_Expecter) FindProjectRoot() *Config_FindProjectRoot_Call {
	return &Config_FindProjectRoot_Call{Call: _e.mock.On("FindProjectRoot")}
}

func (_c *Config_FindProjectRoot_Call) Run(run func()) *Config_FindProjectRoot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Config_FindProjectRoot_Call) Return(s string, err error) *Config_FindProjectRoot_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Config_FindProjectRoot_Call) RunAndReturn(run func() (string, error)) *Config_FindProjectRoot_Call {
	_c.Call.Return(run)
	return _c
}

// ProjectSlug provides a mock function for the type Config
func (_mock *Config) ProjectSlug() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProjectSlug")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Config_ProjectSlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProjectSlug'
type Config_ProjectSlug_Call struct {
	*mock.Call
}

// ProjectSlug is a helper method to define mock.On call
func (_e *Config_Expecter) ProjectSlug() *Config_ProjectSlug_Call {
	return &Config_ProjectSlug_Call{Call: _e.mock.On("ProjectSlug")}
}

func (_c *Config_ProjectSlug_Call) Run(run func()) *Config_ProjectSlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Config_ProjectSlug_Call) Return(s string, err error) *Config_ProjectSlug_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Config_ProjectSlug_Call) RunAndReturn(run func() (string, error)) *Config_ProjectSlug_Call {
	_c.Call.Return(run)
	return _c
}
