// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewDB creates a new instance of DB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *DB {
	mock := &DB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DB is an autogenerated mock type for the DB type
type DB struct {
	mock.Mock
}

type DB_Expecter struct {
	mock *mock.Mock
}

func (_m *DB) EXPECT() *DB_Expecter {
	return &DB_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type DB
func (_mock *DB) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type DB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *DB_Expecter) Close() *DB_Close_Call {
	return &DB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *DB_Close_Call) Run(run func()) *DB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DB_Close_Call) Return(err error) *DB_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DB_Close_Call) RunAndReturn(run func() error) *DB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SQLDB provides a mock function for the type DB
func (_mock *DB) SQLDB() *sql.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SQLDB")
	}

	var r0 *sql.DB
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	return r0
}

// DB_SQLDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SQLDB'
type DB_SQLDB_Call struct {
	*mock.Call
}

// SQLDB is a helper method to define mock.On call
func (_e *DB_Expecter) SQLDB() *DB_SQLDB_Call {
	return &DB_SQLDB_Call{Call: _e.mock.On("SQLDB")}
}

func (_c *DB_SQLDB_Call) Run(run func()) *DB_SQLDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DB_SQLDB_Call) Return(dB *sql.DB) *DB_SQLDB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *DB_SQLDB_Call) RunAndReturn(run func() *sql.DB) *DB_SQLDB_Call {
	_c.Call.Return(run)
	return _c
}
