// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"database/sql"

	"github.com/beabys/ilnamiqui/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewDBOpener creates a new instance of DBOpener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBOpener(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBOpener {
	mock := &DBOpener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DBOpener is an autogenerated mock type for the DBOpener type
type DBOpener struct {
	mock.Mock
}

type DBOpener_Expecter struct {
	mock *mock.Mock
}

func (_m *DBOpener) EXPECT() *DBOpener_Expecter {
	return &DBOpener_Expecter{mock: &_m.Mock}
}

// NewDB provides a mock function for the type DBOpener
func (_mock *DBOpener) NewDB(path string) (service.DB, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for NewDB")
	}

	var r0 service.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (service.DB, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) service.DB); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DBOpener_NewDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewDB'
type DBOpener_NewDB_Call struct {
	*mock.Call
}

// NewDB is a helper method to define mock.On call
//   - path string
func (_e *DBOpener_Expecter) NewDB(path interface{}) *DBOpener_NewDB_Call {
	return &DBOpener_NewDB_Call{Call: _e.mock.On("NewDB", path)}
}

func (_c *DBOpener_NewDB_Call) Run(run func(path string)) *DBOpener_NewDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DBOpener_NewDB_Call) Return(dB service.DB, err error) *DBOpener_NewDB_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *DBOpener_NewDB_Call) RunAndReturn(run func(path string) (service.DB, error)) *DBOpener_NewDB_Call {
	_c.Call.Return(run)
	return _c
}

// RunMigrations provides a mock function for the type DBOpener
func (_mock *DBOpener) RunMigrations(sqlDB *sql.DB) error {
	ret := _mock.Called(sqlDB)

	if len(ret) == 0 {
		panic("no return value specified for RunMigrations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*sql.DB) error); ok {
		r0 = returnFunc(sqlDB)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DBOpener_RunMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunMigrations'
type DBOpener_RunMigrations_Call struct {
	*mock.Call
}

// RunMigrations is a helper method to define mock.On call
//   - sqlDB *sql.DB
func (_e *DBOpener_Expecter) RunMigrations(sqlDB interface{}) *DBOpener_RunMigrations_Call {
	return &DBOpener_RunMigrations_Call{Call: _e.mock.On("RunMigrations", sqlDB)}
}

func (_c *DBOpener_RunMigrations_Call) Run(run func(sqlDB *sql.DB)) *DBOpener_RunMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *sql.DB
		if args[0] != nil {
			arg0 = args[0].(*sql.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *DBOpener_RunMigrations_Call) Return(err error) *DBOpener_RunMigrations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *DBOpener_RunMigrations_Call) RunAndReturn(run func(sqlDB *sql.DB) error) *DBOpener_RunMigrations_Call {
	_c.Call.Return(run)
	return _c
}
