// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/beabys/ilnamiqui/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type Service
func (_mock *Service) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Service_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Service_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Service_Expecter) Close() *Service_Close_Call {
	return &Service_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *Service_Close_Call) Run(run func()) *Service_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Service_Close_Call) Return(err error) *Service_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Service_Close_Call) RunAndReturn(run func() error) *Service_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Service
func (_mock *Service) Delete(ctx context.Context, req *service.DeleteRequest) (*service.DeleteResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *service.DeleteResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.DeleteRequest) (*service.DeleteResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.DeleteRequest) *service.DeleteResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.DeleteResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.DeleteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Service_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.DeleteRequest
func (_e *Service_Expecter) Delete(ctx interface{}, req interface{}) *Service_Delete_Call {
	return &Service_Delete_Call{Call: _e.mock.On("Delete", ctx, req)}
}

func (_c *Service_Delete_Call) Run(run func(ctx context.Context, req *service.DeleteRequest)) *Service_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.DeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*service.DeleteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Delete_Call) Return(deleteResponse *service.DeleteResponse, err error) *Service_Delete_Call {
	_c.Call.Return(deleteResponse, err)
	return _c
}

func (_c *Service_Delete_Call) RunAndReturn(run func(ctx context.Context, req *service.DeleteRequest) (*service.DeleteResponse, error)) *Service_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function for the type Service
func (_mock *Service) EndSession(ctx context.Context, req *service.EndSessionRequest) (*service.EndSessionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 *service.EndSessionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.EndSessionRequest) (*service.EndSessionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.EndSessionRequest) *service.EndSessionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.EndSessionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.EndSessionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type Service_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.EndSessionRequest
func (_e *Service_Expecter) EndSession(ctx interface{}, req interface{}) *Service_EndSession_Call {
	return &Service_EndSession_Call{Call: _e.mock.On("EndSession", ctx, req)}
}

func (_c *Service_EndSession_Call) Run(run func(ctx context.Context, req *service.EndSessionRequest)) *Service_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.EndSessionRequest
		if args[1] != nil {
			arg1 = args[1].(*service.EndSessionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_EndSession_Call) Return(endSessionResponse *service.EndSessionResponse, err error) *Service_EndSession_Call {
	_c.Call.Return(endSessionResponse, err)
	return _c
}

func (_c *Service_EndSession_Call) RunAndReturn(run func(ctx context.Context, req *service.EndSessionRequest) (*service.EndSessionResponse, error)) *Service_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type Service
func (_mock *Service) Init(ctx context.Context, req *service.InitRequest) (*service.InitResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 *service.InitResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.InitRequest) (*service.InitResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.InitRequest) *service.InitResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.InitResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.InitRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type Service_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.InitRequest
func (_e *Service_Expecter) Init(ctx interface{}, req interface{}) *Service_Init_Call {
	return &Service_Init_Call{Call: _e.mock.On("Init", ctx, req)}
}

func (_c *Service_Init_Call) Run(run func(ctx context.Context, req *service.InitRequest)) *Service_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.InitRequest
		if args[1] != nil {
			arg1 = args[1].(*service.InitRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Init_Call) Return(initResponse *service.InitResponse, err error) *Service_Init_Call {
	_c.Call.Return(initResponse, err)
	return _c
}

func (_c *Service_Init_Call) RunAndReturn(run func(ctx context.Context, req *service.InitRequest) (*service.InitResponse, error)) *Service_Init_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function for the type Service
func (_mock *Service) ListKeys(ctx context.Context, req *service.ListKeysRequest) (*service.ListKeysResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 *service.ListKeysResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.ListKeysRequest) (*service.ListKeysResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.ListKeysRequest) *service.ListKeysResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ListKeysResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.ListKeysRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type Service_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.ListKeysRequest
func (_e *Service_Expecter) ListKeys(ctx interface{}, req interface{}) *Service_ListKeys_Call {
	return &Service_ListKeys_Call{Call: _e.mock.On("ListKeys", ctx, req)}
}

func (_c *Service_ListKeys_Call) Run(run func(ctx context.Context, req *service.ListKeysRequest)) *Service_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.ListKeysRequest
		if args[1] != nil {
			arg1 = args[1].(*service.ListKeysRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_ListKeys_Call) Return(listKeysResponse *service.ListKeysResponse, err error) *Service_ListKeys_Call {
	_c.Call.Return(listKeysResponse, err)
	return _c
}

func (_c *Service_ListKeys_Call) RunAndReturn(run func(ctx context.Context, req *service.ListKeysRequest) (*service.ListKeysResponse, error)) *Service_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListSessions provides a mock function for the type Service
func (_mock *Service) ListSessions(ctx context.Context, req *service.ListSessionsRequest) (*service.ListSessionsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListSessions")
	}

	var r0 *service.ListSessionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.ListSessionsRequest) (*service.ListSessionsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.ListSessionsRequest) *service.ListSessionsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ListSessionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.ListSessionsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_ListSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSessions'
type Service_ListSessions_Call struct {
	*mock.Call
}

// ListSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.ListSessionsRequest
func (_e *Service_Expecter) ListSessions(ctx interface{}, req interface{}) *Service_ListSessions_Call {
	return &Service_ListSessions_Call{Call: _e.mock.On("ListSessions", ctx, req)}
}

func (_c *Service_ListSessions_Call) Run(run func(ctx context.Context, req *service.ListSessionsRequest)) *Service_ListSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.ListSessionsRequest
		if args[1] != nil {
			arg1 = args[1].(*service.ListSessionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_ListSessions_Call) Return(listSessionsResponse *service.ListSessionsResponse, err error) *Service_ListSessions_Call {
	_c.Call.Return(listSessionsResponse, err)
	return _c
}

func (_c *Service_ListSessions_Call) RunAndReturn(run func(ctx context.Context, req *service.ListSessionsRequest) (*service.ListSessionsResponse, error)) *Service_ListSessions_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type Service
func (_mock *Service) Load(ctx context.Context, req *service.LoadRequest) (*service.LoadResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *service.LoadResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.LoadRequest) (*service.LoadResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.LoadRequest) *service.LoadResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.LoadResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.LoadRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Service_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.LoadRequest
func (_e *Service_Expecter) Load(ctx interface{}, req interface{}) *Service_Load_Call {
	return &Service_Load_Call{Call: _e.mock.On("Load", ctx, req)}
}

func (_c *Service_Load_Call) Run(run func(ctx context.Context, req *service.LoadRequest)) *Service_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.LoadRequest
		if args[1] != nil {
			arg1 = args[1].(*service.LoadRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Load_Call) Return(loadResponse *service.LoadResponse, err error) *Service_Load_Call {
	_c.Call.Return(loadResponse, err)
	return _c
}

func (_c *Service_Load_Call) RunAndReturn(run func(ctx context.Context, req *service.LoadRequest) (*service.LoadResponse, error)) *Service_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type Service
func (_mock *Service) Save(ctx context.Context, req *service.SaveRequest) (*service.SaveResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *service.SaveResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.SaveRequest) (*service.SaveResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.SaveRequest) *service.SaveResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SaveResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.SaveRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Service_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.SaveRequest
func (_e *Service_Expecter) Save(ctx interface{}, req interface{}) *Service_Save_Call {
	return &Service_Save_Call{Call: _e.mock.On("Save", ctx, req)}
}

func (_c *Service_Save_Call) Run(run func(ctx context.Context, req *service.SaveRequest)) *Service_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.SaveRequest
		if args[1] != nil {
			arg1 = args[1].(*service.SaveRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Save_Call) Return(saveResponse *service.SaveResponse, err error) *Service_Save_Call {
	_c.Call.Return(saveResponse, err)
	return _c
}

func (_c *Service_Save_Call) RunAndReturn(run func(ctx context.Context, req *service.SaveRequest) (*service.SaveResponse, error)) *Service_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type Service
func (_mock *Service) Search(ctx context.Context, req *service.SearchRequest) (*service.SearchResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 *service.SearchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.SearchRequest) (*service.SearchResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.SearchRequest) *service.SearchResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.SearchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.SearchRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type Service_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.SearchRequest
func (_e *Service_Expecter) Search(ctx interface{}, req interface{}) *Service_Search_Call {
	return &Service_Search_Call{Call: _e.mock.On("Search", ctx, req)}
}

func (_c *Service_Search_Call) Run(run func(ctx context.Context, req *service.SearchRequest)) *Service_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.SearchRequest
		if args[1] != nil {
			arg1 = args[1].(*service.SearchRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_Search_Call) Return(searchResponse *service.SearchResponse, err error) *Service_Search_Call {
	_c.Call.Return(searchResponse, err)
	return _c
}

func (_c *Service_Search_Call) RunAndReturn(run func(ctx context.Context, req *service.SearchRequest) (*service.SearchResponse, error)) *Service_Search_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function for the type Service
func (_mock *Service) StartSession(ctx context.Context, req *service.StartSessionRequest) (*service.StartSessionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 *service.StartSessionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.StartSessionRequest) (*service.StartSessionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *service.StartSessionRequest) *service.StartSessionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.StartSessionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *service.StartSessionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Service_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type Service_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
//   - req *service.StartSessionRequest
func (_e *Service_Expecter) StartSession(ctx interface{}, req interface{}) *Service_StartSession_Call {
	return &Service_StartSession_Call{Call: _e.mock.On("StartSession", ctx, req)}
}

func (_c *Service_StartSession_Call) Run(run func(ctx context.Context, req *service.StartSessionRequest)) *Service_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *service.StartSessionRequest
		if args[1] != nil {
			arg1 = args[1].(*service.StartSessionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Service_StartSession_Call) Return(startSessionResponse *service.StartSessionResponse, err error) *Service_StartSession_Call {
	_c.Call.Return(startSessionResponse, err)
	return _c
}

func (_c *Service_StartSession_Call) RunAndReturn(run func(ctx context.Context, req *service.StartSessionRequest) (*service.StartSessionResponse, error)) *Service_StartSession_Call {
	_c.Call.Return(run)
	return _c
}
